[workspace]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "gst"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python-lmdb = "*"
pyzmq = "*"
openmpi = "*"
mpi4py = "*"

[pypi-dependencies]
neopyter = "*"
matplotlib = "*"
pandas = "*"

[activation.env]

[tasks]
# ============================================================================
# Full benchmark (both scenarios, all backends)
# ============================================================================
bench = "mpiexec -n 4 python benchmark_mpi.py --scenario both"
bench-small = "mpiexec -n 2 python benchmark_mpi.py --scenario both"
bench-large = "mpiexec -n 8 python benchmark_mpi.py --scenario both"

# ============================================================================
# Scenario-specific benchmarks
# ============================================================================
# Shared storage scenario: write once, read N times (optimal for LMDB/SharedMemory)
bench-shared = "mpiexec -n 4 python benchmark_mpi.py --scenario shared"

# Streaming scenario: continuous message passing (optimal for ZeroMQ/MPI)
bench-streaming = "mpiexec -n 4 python benchmark_mpi.py --scenario streaming"

# ============================================================================
# Backend-specific benchmarks
# ============================================================================
bench-lmdb = "mpiexec -n 4 python benchmark_mpi.py --backend lmdb --scenario both"
bench-shm = "mpiexec -n 4 python benchmark_mpi.py --backend shm --scenario both"
bench-zmq = "mpiexec -n 4 python benchmark_mpi.py --backend zmq --scenario both"
bench-mpi = "mpiexec -n 4 python benchmark_mpi.py --backend mpi --scenario both"

# ============================================================================
# Analysis
# ============================================================================
analyze = "python analyze_results.py"

# ============================================================================
# Cleanup
# ============================================================================
clean = { cmd = "rm -rf /dev/shm/bench_* /tmp/lmdb_bench_* /tmp/zmq_bench_*.ipc benchmark_results.json benchmark_plots/ 2>/dev/null || true" }
